import json
import logging
from typing import Dict, Any, Optional
from groq import Groq
from app.core.config import settings

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are a Medical Document Understanding AI Assistant integrated into MediBrief, a clinical report analysis platform.

Your role is to analyze lab reports and prescriptions, and present findings in a clear, professional, patient-friendly format. You do not diagnose — you inform.

RESPONSE FORMAT RULES:
- Use clean markdown with headers (##, ###), bullet points, and bold text.
- Do NOT use emojis anywhere in your response.
- Do NOT use heavy medical jargon.
- Use simple, clear English.
- Always end with a Medical Disclaimer section.

RESPONSE STRUCTURE (follow this exactly):

## Lab Report Analysis

For each biomarker or test found:
- **[Test Name]**: [Value] [Unit]
  - Status: [Normal / Low / High / Borderline]
  - What this means: [1-2 sentence plain-language explanation]

## Overall Health Assessment

- **Current Status**: [brief overall summary based on data]
- **Key Concerns**: [list any abnormal values and why they matter]
- **Positive Findings**: [list any values in normal range]

## Recommended Next Steps

- [Actionable, non-diagnostic suggestions]

## Medical Disclaimer

This analysis is generated by AI for informational purposes only and does not constitute medical advice, diagnosis, or treatment. Always consult a licensed healthcare professional before making any medical decisions.

SAFETY RULES:
- Never provide a final diagnosis.
- Never recommend specific medications or dosages.
- Never provide emergency treatment instructions.
- If values are critically abnormal, always say "Seek immediate medical attention."
"""

PRESCRIPTION_SYSTEM_PROMPT = """You are a Medical Document Understanding AI Assistant integrated into MediBrief.

Your role is to interpret prescription data extracted from documents and explain it clearly to patients.

RESPONSE FORMAT RULES:
- Use clean markdown with headers and bullet points.
- Do NOT use emojis.
- Do NOT use heavy medical jargon.
- Use simple, clear English.

RESPONSE STRUCTURE (follow this exactly):

## Prescription Summary

For each medicine found:
### [Medicine Name]
- **Purpose**: [What condition this treats]
- **How it works**: [Simple, plain-language mechanism]
- **Dosage & Frequency**: [As extracted from document]
- **Duration**: [As extracted, or "As directed by physician"]
- **Common Side Effects**: [List 2-3 most common side effects]
- **Generic Alternatives**: [List generic/low-cost Indian equivalents with same active salt, if known]
  - Note: Consult a pharmacist before switching medicines.

## Important Warnings

- [Any interactions or warnings relevant to the medicines listed]
- Always take medicines as prescribed. Do not alter dose or frequency without consulting your doctor.

## Medical Disclaimer

This information is for educational purposes only. Always consult your prescribing doctor or a qualified pharmacist before making any changes to your medications.
"""

VISION_USER_PROMPT = (
    "This image contains a medical lab report or prescription. "
    "Please carefully read ALL text, numbers, test names, values, units, and reference ranges visible in the image. "
    "Then provide a complete analysis following the response structure in your instructions. "
    "Extract every biomarker and test result you can see — do not skip any values."
)


class AIService:
    def __init__(self):
        self.client = Groq(api_key=settings.GROQ_API_KEY)
        self.text_model = "llama-3.3-70b-versatile"
        self.vision_model = "llama-3.2-11b-vision-preview"

    def generate_health_summary(
        self,
        biomarkers: Dict[str, Any],
        raw_text: str = "",
        history: Optional[list] = None
    ) -> str:
        """
        Generates a health summary from structured biomarkers or raw text.
        Called when native PDF text extraction succeeds.
        """
        try:
            if biomarkers:
                payload = {
                    "extracted_biomarkers": biomarkers,
                    "historical_reports": history if history else "No prior reports on file."
                }
                user_content = (
                    "Analyze the following structured lab report data and provide a complete health summary.\n\n"
                    f"```json\n{json.dumps(payload, indent=2)}\n```"
                )
            else:
                sanitized_text = raw_text[:4000].strip()
                if not sanitized_text:
                    raise ValueError("empty_text")
                user_content = (
                    "The following text was extracted from a medical lab report. "
                    "Please read it carefully and provide a complete health summary, "
                    "identifying all biomarkers, test values, and health indicators present:\n\n"
                    f"```\n{sanitized_text}\n```"
                )

            response = self.client.chat.completions.create(
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": user_content}
                ],
                model=self.text_model,
                temperature=0.2,
                max_tokens=2000,
            )
            return response.choices[0].message.content

        except Exception as e:
            logger.error(f"Failed to generate AI summary: {str(e)}")
            raise ValueError(f"AI Generation Error: {str(e)}")

    def analyze_with_vision(
        self,
        images_base64: list,
        mime_type: str = "image/jpeg",
        is_prescription: bool = False
    ) -> str:
        """
        Analyzes medical document images (scanned PDFs or uploaded images)
        using Groq's vision model. No OCR/Tesseract required.
        Accepts a list of base64 image strings (one per page).
        """
        try:
            # Build multimodal content: images first, then the prompt
            content = []
            for img_b64 in images_base64[:3]:  # cap at 3 pages/images
                content.append({
                    "type": "image_url",
                    "image_url": {
                        "url": f"data:{mime_type};base64,{img_b64}"
                    }
                })
            content.append({
                "type": "text",
                "text": VISION_USER_PROMPT
            })

            system = PRESCRIPTION_SYSTEM_PROMPT if is_prescription else SYSTEM_PROMPT

            response = self.client.chat.completions.create(
                messages=[
                    {"role": "system", "content": system},
                    {"role": "user", "content": content}
                ],
                model=self.vision_model,
                temperature=0.2,
                max_tokens=2000,
            )
            return response.choices[0].message.content

        except Exception as e:
            logger.error(f"Vision analysis failed: {str(e)}")
            raise ValueError(f"Vision Analysis Error: {str(e)}")

    def analyze_prescription(self, prescription_text: str) -> str:
        """
        Analyzes prescription text and returns structured medicine information.
        """
        try:
            user_content = (
                "Analyze the following prescription text extracted from a medical document "
                "and provide a complete breakdown for each medicine mentioned:\n\n"
                f"```\n{prescription_text[:3000].strip()}\n```"
            )

            response = self.client.chat.completions.create(
                messages=[
                    {"role": "system", "content": PRESCRIPTION_SYSTEM_PROMPT},
                    {"role": "user", "content": user_content}
                ],
                model=self.text_model,
                temperature=0.2,
                max_tokens=2000,
            )
            return response.choices[0].message.content

        except Exception as e:
            logger.error(f"Failed to analyze prescription: {str(e)}")
            raise ValueError(f"Prescription AI Error: {str(e)}")
