import json
import logging
from typing import Dict, Any, Optional
from groq import Groq
from app.core.config import settings

logger = logging.getLogger(__name__)

# No emojis — clean, professional system prompt
SYSTEM_PROMPT = """You are a Medical Document Understanding AI Assistant integrated into MediBrief, a clinical report analysis platform.

Your role is to analyze structured biomarker data from lab reports and prescriptions, and present findings in a clear, professional, patient-friendly format. You do not diagnose — you inform.

RESPONSE FORMAT RULES:
- Use clean markdown with headers (##, ###), bullet points, and bold text.
- Do NOT use emojis anywhere in your response.
- Do NOT use heavy medical jargon.
- Use simple, clear English.
- Always end with a Medical Disclaimer section.

RESPONSE STRUCTURE (follow this exactly):

## Lab Report Analysis

For each biomarker provided:
- **[Test Name]**: [Value] [Unit]
  - Status: [Normal / Low / High / Borderline]
  - What this means: [1-2 sentence plain-language explanation]

## Overall Health Assessment

- **Current Status**: [brief overall summary based on data]
- **Key Concerns**: [list any abnormal values and why they matter]
- **Positive Findings**: [list any values in normal range]

## Recommended Next Steps

- [Actionable, non-diagnostic suggestions — e.g. "Consult a physician about elevated cholesterol", "Consider lifestyle changes for borderline glucose"]

## Medical Disclaimer

This analysis is generated by AI for informational purposes only and does not constitute medical advice, diagnosis, or treatment. Always consult a licensed healthcare professional before making any medical decisions.

SAFETY RULES:
- Never provide a final diagnosis.
- Never recommend specific medications or dosages.
- Never provide emergency treatment instructions.
- If values are critically abnormal, always say "Seek immediate medical attention."
"""

PRESCRIPTION_SYSTEM_PROMPT = """You are a Medical Document Understanding AI Assistant integrated into MediBrief.

Your role is to interpret prescription data extracted from documents and explain it clearly to patients.

RESPONSE FORMAT RULES:
- Use clean markdown with headers and bullet points.
- Do NOT use emojis.
- Do NOT use heavy medical jargon.
- Use simple, clear English.

RESPONSE STRUCTURE (follow this exactly):

## Prescription Summary

For each medicine found:
### [Medicine Name]
- **Purpose**: [What condition this treats]
- **How it works**: [Simple, plain-language mechanism]
- **Dosage & Frequency**: [As extracted from document]
- **Duration**: [As extracted, or "As directed by physician"]
- **Common Side Effects**: [List 2-3 most common side effects]
- **Generic Alternatives**: [List generic/low-cost Indian equivalents with same active salt, if known]
  - Note: Consult a pharmacist before switching medicines.

## Important Warnings

- [Any interactions or warnings relevant to the medicines listed]
- Always take medicines as prescribed. Do not alter dose or frequency without consulting your doctor.

## Medical Disclaimer

This information is for educational purposes only. Always consult your prescribing doctor or a qualified pharmacist before making any changes to your medications.
"""


class AIService:
    def __init__(self):
        self.client = Groq(api_key=settings.GROQ_API_KEY)
        self.model = "llama-3.3-70b-versatile"

    def generate_health_summary(
        self,
        biomarkers: Dict[str, Any],
        raw_text: str = "",
        history: Optional[list] = None
    ) -> str:
        """
        Generates a health summary.
        Sends structured JSON biomarkers when available, 
        falls back to raw text for AI analysis when parsing yields no results.
        """
        try:
            if biomarkers:
                # Preferred path: send only clean structured data
                payload = {
                    "extracted_biomarkers": biomarkers,
                    "historical_reports": history if history else "No prior reports on file."
                }
                user_content = (
                    "Analyze the following structured lab report data and provide a complete health summary.\n\n"
                    f"```json\n{json.dumps(payload, indent=2)}\n```"
                )
            else:
                # Fallback: send sanitized raw text (trimmed to avoid token overflow)
                sanitized_text = raw_text[:3000].strip()
                user_content = (
                    "No structured biomarkers could be automatically extracted from this report. "
                    "Please analyze the following raw text from the lab report and extract any "
                    "relevant health information you can identify:\n\n"
                    f"```\n{sanitized_text}\n```"
                )

            response = self.client.chat.completions.create(
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": user_content}
                ],
                model=self.model,
                temperature=0.2,
                max_tokens=2000,
            )
            return response.choices[0].message.content

        except Exception as e:
            logger.error(f"Failed to generate AI summary: {str(e)}")
            raise ValueError(f"AI Generation Error: {str(e)}")

    def analyze_prescription(self, prescription_text: str) -> str:
        """
        Analyzes prescription text and returns structured medicine information.
        """
        try:
            user_content = (
                "Analyze the following prescription text extracted from a medical document "
                "and provide a complete breakdown for each medicine mentioned:\n\n"
                f"```\n{prescription_text[:3000].strip()}\n```"
            )

            response = self.client.chat.completions.create(
                messages=[
                    {"role": "system", "content": PRESCRIPTION_SYSTEM_PROMPT},
                    {"role": "user", "content": user_content}
                ],
                model=self.model,
                temperature=0.2,
                max_tokens=2000,
            )
            return response.choices[0].message.content

        except Exception as e:
            logger.error(f"Failed to analyze prescription: {str(e)}")
            raise ValueError(f"Prescription AI Error: {str(e)}")
